# Site settings
title: CS051 Pomona College
description: >
  A companion site for the CS051 Introduction to Computer Science Course
  offered at Pomona College dedicated to the documentation of implementing
  the Git and GitHub in the lab environment.
url:
github_username: git-at-pomona

# Build settings
markdown: kramdown
